services:
    activity_listener:
        class: Ben\UserBundle\Listener\ActivityListener
        arguments: ["@security.context", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
    ben.stats_handler:
        class: Ben\UserBundle\Stats\StatsHandler
        arguments: ["@doctrine.orm.entity_manager"]
